### ISSUE TITLE
bosh-gen dependencies need to be updated to include mime-types gem

### ISSUE THREAD

**Issue by 7hunderbird** [cloudfoundry-community/bosh-gen#87]
After installing `bosh-gen` a run through to complete a `bosh-gen new <release_name>` did not complete because it was missing a required library of mime-types.

Let's update the gem specifications so this gets installed with the `bosh-gen` gem.

**Comment by drnic** [comment]
Perhaps it used to get installed by fog; but now it's optional albeit necessary.
PR to fix gemspec would be great






On Fri, Nov 4, 2016 at 5:37 AM +1000, "Tyler Bird" <notifications@github.com> wrote:












After installing bosh-gen a run through to complete a bosh-gen new <release_name> did not complete because it was missing a required library of mime-types.


Let's update the gem specifications so this gets installed with the bosh-gen gem.

**Comment by drnic** [comment]
mime-types is now in the gemspec
